// NOTE: This file is regenerated by scaffold.mjs on every init/add based on
// the modules listed in .scaffold-state.json. If you're copying this skill by
// hand, see references/wire-up.md for the manual wire-up recipe.
import 'dotenv/config';
import { env } from './config/env.js';
import { createApp } from './server/http.js';
import { logger } from './lib/logger.js';
import { installShutdown, onShutdown } from './lib/shutdown.js';
import { errorHandler, notFoundHandler } from './middleware/error.basic.js';

async function main() {
  installShutdown(env.SHUTDOWN_TIMEOUT_MS);

  const app = createApp();

  app.use(notFoundHandler);
  app.use(errorHandler);

  const server = app.listen(env.PORT, () => {
    logger.info({ port: env.PORT, env: env.NODE_ENV }, 'service started');
  });

  onShutdown('http', () => new Promise<void>((r) => server.close(() => r())));
}

main().catch((err) => {
  logger.error({ err }, 'fatal startup error');
  process.exit(1);
});
